# Site settings
title: Ruby Fore
email: your-email@domain.com
url: rubyfore.github.io/grayscale-theme-rfore
description:  

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FAF9F6'
  links: '#219ab3'

# gallery settings
imagesurl: "./img/"
thumbsurl: "./img/"


# Footer settings
footer:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ruby-fore-851049106/ 
  - title: github
    url: https://github.com/RubyFore 


# Build settings
markdown: kramdown
permalink: pretty
